import streamlit as st
from datetime import date, timedelta
from services import storage_service as storage
from services import cognee_service as cognee_svc
from services import query_service as query
from utils.helpers import cognee_status_banner, ai_insight_box, stat_card, empty_state
from utils.styles import inject_styles

st.set_page_config(page_title="Reports | ThreadTrace", page_icon="📋", layout="wide")
inject_styles()

st.markdown("""
<h1 style="margin-bottom:4px;">📋 Reports & Export</h1>
<p style="color:#6b7280;margin-bottom:20px;">
Statistics, AI caseload analysis, and CSV export</p>
""", unsafe_allow_html=True)
cognee_status_banner()

report = query.generate_report()

# ── Metrics ───────────────────────────────────────────────────────────────────
m1, m2, m3, m4, m5, m6 = st.columns(6)
with m1: stat_card("Total Cases",      str(report["total"]),                  "📁", "#6366f1")
with m2: stat_card("Active",           str(report["active"]),                 "🟢", "#10b981")
with m3: stat_card("Closed",           str(report["closed"]),                 "✅", "#6b7280")
with m4: stat_card("Total Follow-Ups", str(report["total_followups"]),        "📝", "#8b5cf6")
with m5: stat_card("Avg Follow-Ups",   str(report["avg_followups_per_case"]), "📊", "#6366f1")
with m6: stat_card("Missing Docs",     str(report["missing_docs"]),           "📄", "#f59e0b")

st.markdown("<div style='height:20px'></div>", unsafe_allow_html=True)
tab_stats, tab_ai, tab_export = st.tabs(["📊 Statistics", "🧠 AI Insights", "📥 Export"])

# ══════════ TAB 1: Statistics ══════════
with tab_stats:
    cl, cr = st.columns(2, gap="large")

    with cl:
        if report["by_goal"]:
            st.markdown("#### Cases by Goal")
            st.bar_chart(report["by_goal"])
        if report["by_location"]:
            st.markdown("#### Cases by Location (Top 10)")
            top = dict(sorted(report["by_location"].items(),
                              key=lambda x: x[1], reverse=True)[:10])
            st.bar_chart(top)

    with cr:
        st.markdown("#### Deadline Status")
        st.bar_chart({
            "Overdue":       report["overdue_deadline_count"],
            "Due this week": report["thisweek_deadline_count"],
            "On track":      max(0, report["active"]
                                 - report["overdue_deadline_count"]
                                 - report["thisweek_deadline_count"]),
        })
        if report["activity_by_day"]:
            st.markdown("#### Follow-Up Activity (Last 14 Days)")
            act = {}
            for i in range(13, -1, -1):
                d = (date.today() - timedelta(days=i)).isoformat()
                act[d] = report["activity_by_day"].get(d, 0)
            st.bar_chart(act)

    st.divider()
    st.markdown("#### 👥 Volunteer Workload")
    wl = report["volunteer_workload"]
    if wl:
        st.dataframe([{
            "Volunteer": w["volunteer"], "Active Cases": w["cases"],
            "Urgent": w["urgent"], "Overdue Follow-Up": w["overdue"],
        } for w in wl], use_container_width=True, hide_index=True)
    else:
        empty_state("👥", "No active cases", "")

    st.divider()
    st.markdown("#### 📄 Missing Documents Breakdown")
    # Use the public list_documents function — no private _load access
    all_docs = []
    for c in storage.list_cases():
        all_docs.extend(storage.list_documents(c["case_id"]))
    missing_docs = [d for d in all_docs if d["status"] == "missing"]

    if missing_docs:
        by_type = {}
        for d in missing_docs:
            by_type[d["doc_name"]] = by_type.get(d["doc_name"], 0) + 1
        st.bar_chart(dict(sorted(by_type.items(), key=lambda x: x[1], reverse=True)))

        cases_map = {c["case_id"]: c["student_name"] for c in storage.list_cases()}
        st.dataframe([{
            "Student":  cases_map.get(d["case_id"], d["case_id"]),
            "Document": d["doc_name"],
            "Notes":    d.get("notes", ""),
        } for d in missing_docs], use_container_width=True, hide_index=True)
    else:
        st.markdown("""
        <div style="background:rgba(16,185,129,0.08);border:1px solid rgba(16,185,129,0.25);
        border-radius:12px;padding:18px;text-align:center;color:#10b981;font-weight:600;">
        🎉 No missing documents across all cases!
        </div>""", unsafe_allow_html=True)

# ══════════ TAB 2: AI Insights ══════════
with tab_ai:
    st.markdown("#### 🧠 Cognee AI Caseload Analysis")
    st.caption(
        "Generated by Cognee reasoning across all case memory — "
        "follow-up notes, blockers, promises, and context.")

    all_case_ids = [c["case_id"] for c in storage.list_cases()]
    if not cognee_svc.cognee_available():
        st.warning("Configure Cognee Cloud to enable AI insights.", icon="🔑")
    elif not all_case_ids:
        empty_state("📁", "No cases yet", "Add cases to generate insights")
    else:
        insights = {
            "📋 Full Caseload Summary": (
                "Analyze all cases: 1) most common blockers, 2) cases needing urgent "
                "attention, 3) patterns in missing documents, 4) one concrete recommendation."
            ),
            "🚧 Systemic Blockers": (
                "What are the systemic or recurring blockers across all cases? "
                "What do they reveal about gaps in the support process? "
                "What could the NGO do to address these proactively?"
            ),
            "⚠️ Risk Analysis": (
                "Which students are at highest risk of not achieving their goal? "
                "For each, explain why: deadline proximity, unresolved blockers, "
                "no recent contact, or missing documents. Rank by urgency."
            ),
            "✅ What's Working": (
                "Which cases are progressing well? What actions or volunteer behaviors "
                "correlate with cases moving forward? What can we learn from successful cases?"
            ),
            "📊 Process Recommendations": (
                "Based on patterns in all case follow-ups and blockers, "
                "what 3 concrete process improvements would have the biggest "
                "positive impact on student outcomes?"
            ),
        }

        chosen = st.selectbox("Choose insight type", list(insights.keys()))
        if st.button("🔍 Generate AI Insight", type="primary", use_container_width=True):
            with st.spinner(f"Generating: {chosen}..."):
                result = cognee_svc.recall_across_cases(insights[chosen], all_case_ids)
            ai_insight_box(chosen, result)
            st.session_state[f"rpt_{chosen}"] = result
        elif f"rpt_{chosen}" in st.session_state:
            ai_insight_box(chosen, st.session_state[f"rpt_{chosen}"])

        st.divider()
        st.markdown("#### 💬 Custom Analysis")
        custom_q = st.text_area("Ask anything about your caseload",
            placeholder="e.g. What are the top 3 actions the team should take this week?",
            height=80)
        if st.button("Run Query", type="primary") and custom_q:
            with st.spinner("Querying Cognee..."):
                result = cognee_svc.recall_across_cases(custom_q, all_case_ids)
            ai_insight_box("Custom Query Result", result)

# ══════════ TAB 3: Export ══════════
with tab_export:
    st.markdown("#### 📥 Download Data")
    e1, e2 = st.columns(2, gap="large")

    with e1:
        st.markdown("""
        <div style="background:rgba(99,102,241,0.06);border:1px solid rgba(99,102,241,0.2);
        border-radius:12px;padding:20px 22px;">
          <div style="font-weight:700;margin-bottom:6px;">📁 Cases CSV</div>
          <div style="color:#6b7280;font-size:0.85rem;margin-bottom:14px;">
          All case records including status, volunteer, deadline, contact info.</div>
        """, unsafe_allow_html=True)
        cases_csv = query.export_cases_csv()
        if cases_csv:
            st.download_button("⬇️ Download Cases CSV", data=cases_csv,
                file_name=f"ThreadTrace_cases_{date.today().isoformat()}.csv",
                mime="text/csv", use_container_width=True, type="primary")
        else:
            st.info("No cases to export.")
        st.markdown("</div>", unsafe_allow_html=True)

    with e2:
        st.markdown("""
        <div style="background:rgba(139,92,246,0.06);border:1px solid rgba(139,92,246,0.2);
        border-radius:12px;padding:20px 22px;">
          <div style="font-weight:700;margin-bottom:6px;">📝 Follow-Ups CSV</div>
          <div style="color:#6b7280;font-size:0.85rem;margin-bottom:14px;">
          All follow-up logs with notes, blockers, next steps, dates.</div>
        """, unsafe_allow_html=True)
        fups_csv = query.export_followups_csv()
        if fups_csv:
            st.download_button("⬇️ Download Follow-Ups CSV", data=fups_csv,
                file_name=f"ThreadTrace_followups_{date.today().isoformat()}.csv",
                mime="text/csv", use_container_width=True, type="primary")
        else:
            st.info("No follow-ups to export.")
        st.markdown("</div>", unsafe_allow_html=True)

    st.divider()
    st.markdown("#### All Cases Preview")
    all_cases = storage.list_cases()
    if all_cases:
        rows = []
        for c in all_cases:
            rows.append({
                "ID": c["case_id"], "Student": c["student_name"],
                "Location": c["location"], "Goal": c["goal"],
                "Deadline": c["deadline"], "Status": query.urgency_label(c),
                "Volunteer": c["assigned_volunteer"],
                "Follow-Ups": len(storage.list_followups(c["case_id"])),
                "Missing Docs": query.missing_docs_count(c["case_id"]),
            })
        st.dataframe(rows, use_container_width=True, hide_index=True)
